name: kd
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchtext=0.13.1
  - torchvision=0.13.1
  - tqdm=4.64.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - accelerate==0.12.0
    - adal==1.2.7
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - alembic==1.8.1
    - argcomplete==2.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - azure-common==1.1.28
    - azure-core==1.25.1
    - azure-graphrbac==0.61.1
    - azure-identity==1.7.0
    - azure-mgmt-authorization==2.0.0
    - azure-mgmt-containerregistry==9.1.0
    - azure-mgmt-core==1.3.2
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==20.1.0
    - azure-mgmt-storage==19.1.0
    - azure-storage-blob==12.13.1
    - azure-storage-file-datalake==12.8.0
    - azure-storage-file-share==12.9.0
    - azure-storage-queue==12.4.0
    - azureml-core==1.41.0.post1
    - azureml-dataprep==4.0.4
    - azureml-dataprep-native==38.0.0
    - azureml-dataprep-rslex==2.6.3
    - azureml-dataset-runtime==1.43.0
    - azureml-mlflow==1.41.0.post1
    - backcall==0.2.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==4.0.0
    - beautifulsoup4==4.11.1
    - bert-score==0.3.11
    - bleach==5.0.1
    - blis==0.9.1
    - cachetools==5.2.0
    - catalogue==2.0.8
    - click==8.1.3
    - cloudpickle==2.2.0
    - colorama==0.4.5
    - confection==0.0.1
    - contextlib2==21.6.0
    - contourpy==1.0.5
    - cryptography==36.0.2
    - cycler==0.11.0
    - cymem==2.0.6
    - databricks-cli==0.17.3
    - datasets==1.18.4
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - distro==1.7.0
    - docker==5.0.3
    - docker-pycreds==0.4.0
    - dotnetcore2==3.1.23
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==1.0.0
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - flask==2.2.2
    - fonttools==4.37.3
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gensim==4.2.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.1
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.3
    - grpcio==1.49.1
    - gunicorn==20.1.0
    - huggingface-hub==0.9.1
    - humanfriendly==10.0
    - importlib-metadata==4.12.0
    - ipykernel==6.15.3
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - isodate==0.6.1
    - itsdangerous==2.1.2
    - jarowinkler==1.2.1
    - jedi==0.18.1
    - jeepney==0.8.0
    - jinja2==3.1.2
    - jiwer==2.5.1
    - jmespath==0.10.0
    - joblib==1.2.0
    - jsonpickle==2.2.0
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.3.5
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - knack==0.9.0
    - langcodes==3.3.0
    - levenshtein==0.20.2
    - lxml==4.9.1
    - mako==1.2.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mlflow==1.29.0
    - mlflow-skinny==1.29.0
    - msal==1.19.0
    - msal-extensions==0.3.1
    - msrest==0.7.1
    - msrestazure==0.6.4
    - multidict==6.0.2
    - multiprocess==0.70.13
    - murmurhash==1.0.8
    - nbclient==0.6.8
    - nbconvert==7.0.0
    - nbformat==5.6.0
    - ndg-httpsclient==0.5.1
    - nest-asyncio==1.5.5
    - nltk==3.7
    - notebook==6.4.12
    - oauthlib==3.2.1
    - openai==0.23.1
    - openpyxl==3.0.10
    - packaging==21.3
    - pandas==1.5.0
    - pandas-stubs==1.5.0.221012
    - pandocfilters==1.5.0
    - paramiko==2.11.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pathy==0.6.2
    - patsy==0.5.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkginfo==1.8.3
    - plotly==5.10.0
    - portalocker==2.5.1
    - preshed==3.0.7
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.3
    - promise==2.3
    - prompt-toolkit==3.0.31
    - protobuf==3.19.5
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.2
    - pydeprecate==0.3.2
    - pygments==2.13.0
    - pyjwt==2.5.0
    - pynacl==1.5.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.7.7
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.0
    - querystring-parser==1.2.4
    - rapidfuzz==2.10.0
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - rsa==4.9
    - sacrebleu==2.2.1
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - seaborn==0.12.0
    - secretstorage==3.3.3
    - send2trash==1.8.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.9.0
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - smart-open==5.2.1
    - smmap==5.0.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.1
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - sqlalchemy==1.4.41
    - sqlparse==0.4.3
    - srsly==2.4.4
    - stack-data==0.5.0
    - statsmodels==0.13.2
    - tabulate==0.8.10
    - tdqm==0.0.1
    - tenacity==8.1.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - thinc==8.1.1
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - torchmetrics==0.9.3
    - tornado==6.2
    - traitlets==5.4.0
    - transformers==4.22.1
    - typer==0.4.2
    - types-cryptography==3.3.23
    - types-pytz==2022.4.0.0
    - urllib3==1.26.7
    - wandb==0.13.3
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - xgboost==1.6.2
    - xxhash==3.0.0
    - yarl==1.8.1
    - zipp==3.8.1
